DROP TABLE IF EXISTS owox;
SHOW CREATE DATABASE owox;
USE owox;

DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLIENTS(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRICE FLOAT NOT NULL
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
  ID INT NOT NULL AUTO_INCREMENT,
  CLIENT_ID INT,
  PRODUCT_ID INT
);
